.TH "C:/Users/egomez/Documents/codeblocks/testc22/error.h" 3 "Wed Aug 8 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/egomez/Documents/codeblocks/testc22/error.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBerrorPrint\fP { \fBerrorSizePrint\fP = -101, \fBerrorTypePrint\fP = -102 }"
.br
.RI "\fIenum to enumerate the errors of \fBprint\&.c\fP\&. \fP"
.ti -1c
.RI "enum \fBerrorInterchange\fP { \fBerrorSizeInterchange\fP = -201, \fBerrorTypeInterchange\fP = -202 }"
.br
.RI "\fIenum to enumerate the errors of \fBinterchange\&.c\fP\&. \fP"
.ti -1c
.RI "enum \fBerrorAllocator\fP { \fBerrorSizeAllocator\fP = -301, \fBerrorTypeAllocator\fP = -302, \fBerrorNoAllocate\fP = -303 }"
.br
.RI "\fIenum to enumerate the errors of \fBallocator\&.c\fP\&. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBerrorAllocator\fP"

.PP
enum to enumerate the errors of \fBallocator\&.c\fP\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIerrorSizeAllocator \fP\fP
-301 indicating error of array size 
.TP
\fB\fIerrorTypeAllocator \fP\fP
-301 indicating error of type of array 
.TP
\fB\fIerrorNoAllocate \fP\fP
-301 indicating error of allocation 
.PP
Definition at line 33 of file error\&.h\&.
.SS "enum \fBerrorInterchange\fP"

.PP
enum to enumerate the errors of \fBinterchange\&.c\fP\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIerrorSizeInterchange \fP\fP
-201 indicating error of array size 
.TP
\fB\fIerrorTypeInterchange \fP\fP
-201 indicating error of type of array 
.PP
Definition at line 21 of file error\&.h\&.
.SS "enum \fBerrorPrint\fP"

.PP
enum to enumerate the errors of \fBprint\&.c\fP\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIerrorSizePrint \fP\fP
-101 indicating error of array size 
.TP
\fB\fIerrorTypePrint \fP\fP
-101 indicating error of type of array 
.PP
Definition at line 9 of file error\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
