.TH "C:/Users/egomez/Documents/codeblocks/testc22/interchange.h" 3 "Wed Aug 8 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/egomez/Documents/codeblocks/testc22/interchange.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'allocator\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBInterchangeTotalGeneric\fP (void *a, void *b, int64_t sizeA, int64_t sizeB, int8_t typePointer)"
.br
.RI "\fIThis function interchange the data between to pointers 'a' and 'b'\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void InterchangeTotalGeneric (void *a, void *b, int64_tsizeA, int64_tsizeB, int8_ttypePointer)"

.PP
This function interchange the data between to pointers 'a' and 'b'\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP pointer to the array 'a' 
.br
\fIb\fP pointer to the array 'b' 
.br
\fIsizeA\fP the number of elements of the array 'a' 
.br
\fIsizeB\fP the number of elements of the array 'b' 
.br
\fItypePointer\fP type of the elements of the array 'a' and 'b' 
.RE
.PP

.PP
Definition at line 6 of file interchange\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
