.TH "C:/Users/egomez/Documents/codeblocks/testc22/main.c" 3 "Wed Aug 8 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/egomez/Documents/codeblocks/testc22/main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'print\&.h'\fP
.br
\fC#include 'interchange\&.h'\fP
.br
\fC#include 'allocator\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Definition at line 5 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
