.TH "C:/Users/egomez/Documents/codeblocks/testc22/print.h" 3 "Wed Aug 8 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/egomez/Documents/codeblocks/testc22/print.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'header\&.h'\fP
.br
\fC#include 'error\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPrintArray\fP (void *theArray, int64_t size, uint8_t typePointer)"
.br
.RI "\fIThis function prints the elements belonging to an array\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void PrintArray (void *theArray, int64_tsize, uint8_ttypePointer)"

.PP
This function prints the elements belonging to an array\&. 
.PP
\fBParameters:\fP
.RS 4
\fItheArray\fP pointer to the array 
.br
\fIsize\fP number of elements of the array 
.br
\fItypePointer\fP type of the elements to be printed 
.RE
.PP

.PP
Definition at line 3 of file print\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
